name: Daily cancel check (9AM WIB)

on:
  schedule:
    - cron: "0 2 * * *" # 09:00 WIB = 02:00 UTC
  workflow_dispatch:

jobs:
  call_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: GET to Fly endpoint
        run: |
          curl -sS -X GET "https://taratechapi.fly.dev/api/ecosuite/send-cancel-notification-for-confirmed-reservations-1day-before-reservation-date/?brandId=3CFJB0UV4K"
